import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { VideoControls } from "video-controls.slint";
import { VideoWindow } from "video-window.slint";

export component App inherits Window {

    in property <[string]> video_sources <=> controls.video_sources;
    in-out property <int> current_video_source <=> controls.curr_video_source;
    in property <[string]> framerates <=> controls.fps;
    in-out property <int> curr_fps <=> controls.curr_fps;
    in property <image> video-frame <=> image.video-frame;
    in property <bool> playing <=> controls.playing;

    pure callback toggle-play-pause <=> controls.toggle-play-pause;

    preferred-width: 640px;
    preferred-height: 480px;
    min-width: 640px;
    min-height: 100px;
    title: "Video Noise Analyzer";
    background: #BBBBBBFF;

    VerticalLayout {
        spacing: 5px;
        image := VideoWindow { }

        controls := VideoControls { }
    }
}
