import { Styles } from "styles.slint";
import { ComboBox, VerticalBox } from "std-widgets.slint";

component ContentWindow inherits Rectangle {

    border-radius: 8px;
    background: transparent;
    border-width: 1px;
    border-color: Styles.video_color;

    in property <image> image <=> image.source;
    out property <bool> ta_pressed <=> ta.pressed;

    // actual cursor positions in the GUI
    out property <length> gui_x:
    {
        max(self.gui_img_x1, min(self.gui_img_x2, ta.mouse-x))
    }

    out property <length> gui_y:
    {
        max(self.gui_img_y1, min(self.gui_img_y2, ta.mouse-y))
    }

    // scaled positions that correspond to the real image size
    out property <length> img_x: {
        max(0, min(((ta.mouse-x - gui_img_x1) / scale).round(), self.image.width)) * 1px
    }
    out property <length> img_y: {
        max(0, min(((ta.mouse-y - gui_img_y1) / scale).round(), self.image.height)) * 1px
    }

    // limits TouchArea to image size
    out property <length> scale: {
        min(image.width / image.source.width, image.height / image.source.height);
    }
    out property <length> gui_img_w: {
        image.source.width * scale
    }
    out property <length> gui_img_x1: {
        image.x + (image.width - gui_img_w) / 2.0
    }
    property <length> gui_img_x2: {
        gui_img_x1 + gui_img_w
    }
    out property <length> gui_img_h: {
        image.source.height * scale
    }
    out property <length> gui_img_y1: {
        image.y + (image.height - gui_img_h) / 2.0
    }
    property <length> gui_img_y2: {
        gui_img_y1 + gui_img_h
    }

    pure callback in_image_boundary() -> bool;
    in_image_boundary() => {
        ta.mouse-x >= gui_img_x1 && ta.mouse-x <= gui_img_x2 && ta.mouse-y >= gui_img_y1 && ta.mouse-y <= gui_img_y2
    }

    image := Image {
        width: parent.width;
        height: parent.height;
        image-fit: contain;
        source: @image-url("assets/cat.jpg");
        ta := TouchArea {
            mouse-cursor: in_image_boundary() ? crosshair : default;
        }
    }
}

export component VideoWindow inherits HorizontalLayout {

    in property <int> buffering_percent;
    in property <image> video-frame <=> content.image;

    in-out property <length> noise_x;
    in-out property <length> noise_y;
    in-out property <length> noise_w;
    in-out property <length> noise_h;

    changed noise_x => {
        self.noise_x = max(0, min(self.noise_x, content.image.width * 1px));
        self.noise_w = max(0, min(self.noise_w, content.image.width * 1px - self.noise_x));
    }
    changed noise_y => {
        self.noise_y = max(0, min(self.noise_y, content.image.height * 1px));
        self.noise_h = max(0, min(self.noise_h, content.image.height * 1px - self.noise_y));
    }
    changed noise_w => {
        self.noise_w = max(0, min(self.noise_w, content.image.width * 1px - self.noise_x));
    }
    changed noise_h => {
        self.noise_h = max(0, min(self.noise_h, content.image.height * 1px - self.noise_y));
    }

    property <length> origin_noise_x;
    property <length> origin_noise_y;
    property <length> origin_gui_x;
    property <length> origin_gui_y;

    property <length> gui_x: content.gui_img_x1 + self.noise_x * content.scale / 1px;
    property <length> gui_y: content.gui_img_y1 + self.noise_y * content.scale / 1px;
    property <length> gui_w: self.noise_w * content.scale / 1px;
    property <length> gui_h: self.noise_h * content.scale / 1px;

    pure callback calc_pos(length, length, int) -> length;
    pure callback calc_size(length, length, int) -> length;
    pure callback calc_gui_x() -> length;
    pure callback calc_gui_y() -> length;
    pure callback calc_gui_w() -> length;
    pure callback calc_gui_h() -> length;
    calc_pos(origin, mouse, max_pos) => {
        if (mouse > origin) {
            return max(0px, min(origin, max_pos * 1px));
        }
        max(0px, min(mouse, max_pos * 1px))
    }
    calc_size(origin, mouse, max_size) => {
        let size = (origin - mouse).abs();
        if (max_size < 1) {
            return max(0px, min(size, max_size * 1px));
        }
        if (mouse > origin) {
            return max(0px, min(size, max_size * 1px - origin));
        }
        max(0px, min(size, max_size * 1px - mouse))
    }
    calc_gui_x() => {
        content.gui_img_x1 + calc_pos(root.origin_noise_x, content.img_x, content.image.width) * content.scale / 1px;
    }
    calc_gui_y() => {
        content.gui_img_y1 + calc_pos(root.origin_noise_y, content.img_y, content.image.height) * content.scale / 1px;
    }
    calc_gui_w() => {
        calc_size(root.origin_noise_x, content.img_x, content.image.width) * content.scale / 1px;
    }
    calc_gui_h() => {
        calc_size(root.origin_noise_y, content.img_y, content.image.height) * content.scale / 1px;
    }

    Rectangle {
        content := ContentWindow {
            width <=> root.width;
            height <=> root.height;

            // select noise window
            changed ta_pressed => {
                if (self.ta_pressed) {
                    // button down updates the origin of the noise window
                    root.origin_noise_x = self.img_x;
                    root.origin_noise_y = self.img_y;
                    root.origin_gui_x = self.gui_x;
                    root.origin_gui_y = self.gui_y;
                } else {
                    // button up updates the noise window
                    root.noise_x = calc_pos(root.origin_noise_x, self.img_x, self.image.width);
                    root.noise_y = calc_pos(root.origin_noise_y, self.img_y, self.image.height);
                    root.noise_w = calc_size(root.origin_noise_x, self.img_x, self.image.width);
                    root.noise_h = calc_size(root.origin_noise_y, self.img_y, self.image.height);
                }
            }
        }

        noise := Rectangle {
            x: content.ta_pressed ? calc_gui_x() : root.gui_x;
            y: content.ta_pressed ? calc_gui_y() : root.gui_y;
            width: content.ta_pressed ? calc_gui_w() : root.gui_w;
            height: content.ta_pressed ? calc_gui_h() : root.gui_h;
            border-color: red;
            border-width: 2px;
            opacity: 0.7;
            background: transparent;
        }
    }
}

export component VideoComboBox inherits ComboBox {
    in property <[string]> options;

    model: options;
}

export component VideoText inherits Text {
    text: "example text";
    font-size: 12px;
    font-weight: 600;
    color: Styles.video_color;
}

export component VideoButton inherits Rectangle {

    in property <string> text;

    pure callback clicked();

    width: Math.max(content.width + Styles.padding * 2, 100px);
    height: content.height + Styles.padding * 2;
    border-radius: 8px;
    background: Styles.video_gradient;
    border-width: ta.has-hover ? 2px : 1px;
    border-color: Styles.video_color;

    content := VideoText {
        text: text;
        font-weight: ta.has-hover ? 1000 : 600;
    }

    ta := TouchArea {
        clicked => clicked();
    }
}

export component ChooseDirButton inherits Rectangle {

    in property <string> text;

    callback choose-output-dir();

    width: 30px;
    height: 30px;

    Image {
        width: parent.width;
        height: parent.height;

        source: @image-url("assets/dir.png");
        accessible-label: "Choose output directory";
    }

    Rectangle {
        border-width: ta.has-hover ? 2px : 1px;
        border-color: #000;
        opacity: ta.pressed ? 0.7 : 1.0;
        background: ta.pressed ? darkgray : transparent;
    }

    ta := TouchArea {
        clicked => choose-output-dir();
    }
}

export component InputTextBox inherits Rectangle {

    in-out property <string> text <=> t.text;
    in property <InputType> input_type <=> t.input-type;

    callback edited <=> t.edited;

    clip: true;
    height: 20px;
    background: white;
    border-color: black;
    border-width: 1px;
    preferred-width <=> t.preferred-width;

    t := TextInput {
        text: "Edit me";
        color: black;
        vertical-alignment: center;

        private property <length> margin: 1rem;
        cursor-position-changed(cursor-position) => {
            if cursor-position.x + self.x < margin {
                self.x = - cursor-position.x + margin;
            } else if cursor-position.x + self.x > parent.width - margin - self.text-cursor-width {
                self.x = parent.width - cursor-position.x - margin - self.text-cursor-width;
            }
        }
    }
}

export component VideoInputBox inherits Rectangle {

    in property <string> name <=> vt.text;
    in property <length> boxwidth <=> box.preferred-width;
    in property <LayoutAlignment> alignment <=> h.alignment;
    in-out property <string> val <=> box.text;
    in property <InputType> input_type <=> box.input-type;

    callback edited <=> box.edited;

    h := HorizontalLayout {
        alignment: start;
        vt := VideoText {
            vertical-alignment: center;
            horizontal-alignment: left;
            text: "text:";
        }

        VerticalLayout {
            alignment: center;
            box := InputTextBox {
                text: "0";
            }
        }
    }
}

export component MetricText inherits Text {
    font-weight: 700;
    preferred-width: 250px;
    color: Styles.video_color;
}
