import { Styles } from "styles.slint";
import { ComboBox, VerticalBox } from "std-widgets.slint";

component ContentWindow inherits Rectangle {

    out property <length> ta_x <=> ta.mouse-x;
    out property <length> ta_y <=> ta.mouse-y;
    out property <bool> ta_pressed <=> ta.pressed;
    in property <image> image <=> image.source;

    // limits TouchArea to image size
    property <length> scale: {
        min(image.width / image.source.width, image.height / image.source.height);
    }
    property <length> scaled_image_width: {
        image.source.width * scale
    }
    out property <length> x_left: {
        image.x + (image.width - scaled_image_width) / 2.0
    }
    out property <length> x_right: {
        x_left + scaled_image_width
    }
    property <length> scaled_image_height: {
        image.source.height * scale
    }
    out property <length> y_top: {
        image.y + (image.height - scaled_image_height) / 2.0
    }
    out property <length> y_bottom: {
        y_top + scaled_image_height
    }

    ta := TouchArea {
        mouse-cursor: ta.mouse-x >= x_left && ta.mouse-x <= x_right && ta.mouse-y >= y_top && ta.mouse-y <= y_bottom ? crosshair : default;
    }

    image := Image {
        width: parent.width;
        height: parent.height;
        image-fit: contain;
        source: @image-url("assets/cat.jpg");
    }
}

export component VideoWindow inherits Rectangle {

    min-width: 640px;
    min-height: 360px;
    border-radius: 8px;
    background: transparent;
    border-width: 1px;
    border-color: Styles.video_color;

    in property <int> buffering_percent;
    in property <image> video-frame <=> content.image;

    in-out property <length> noise_x;
    in-out property <length> noise_y;
    in-out property <length> noise_w;
    in-out property <length> noise_h;

    content := ContentWindow { }

    noise := Rectangle {
        x: content.ta_pressed ? content.ta_x : root.noise_x;
        y: content.ta_pressed ? content.ta_y : root.noise_y;
        width: root.noise_w;
        height: root.noise_h;
        opacity: content.ta_pressed ? 0.7 : 0.2;
        background: black;
    }
}

export component VideoComboBox inherits Rectangle {
    background: transparent;

    in-out property <int> current-index <=> cb.current-index;

    callback selected <=> cb.selected;

    in property <[string]> options;
    cb := ComboBox {
        model: options;
    }
}

export component VideoText inherits Text {
    text: "example text";
    font-size: 12px;
    font-weight: 600;
    color: Styles.video_color;
}

export component VideoButton inherits Rectangle {

    in property <string> text;

    pure callback clicked();

    width: Math.max(content.width + Styles.padding * 2, 100px);
    height: content.height + Styles.padding * 2;
    border-radius: 8px;
    background: Styles.video_gradient;
    border-width: ta.has-hover ? 2px : 1px;
    border-color: Styles.video_color;

    content := VideoText {
        text: text;
        font-weight: ta.has-hover ? 1000 : 600;
    }

    ta := TouchArea {
        clicked => clicked();
    }
}

export component ChooseDirButton inherits Rectangle {

    in property <string> text;

    callback choose-output-dir();

    width: 30px;
    height: 30px;

    Image {
        width: parent.width;
        height: parent.height;

        source: @image-url("assets/dir.png");
        accessible-label: "Choose output directory";
    }

    Rectangle {
        border-width: ta.has-hover ? 2px : 1px;
        border-color: #000;
        opacity: ta.pressed ? 0.7 : 1.0;
        background: ta.pressed ? darkgray : transparent;
    }

    ta := TouchArea {
        clicked => choose-output-dir();
    }
}

export component InputTextBox inherits Rectangle {

    in-out property <string> text <=> t.text;
    in property <InputType> input_type <=> t.input-type;

    clip: true;
    height: 20px;
    background: white;
    border-color: black;
    border-width: 1px;

    t := TextInput {
        text: "Edit me";
        color: black;
        vertical-alignment: center;

        private property <length> margin: 1rem;
        cursor-position-changed(cursor-position) => {
            if cursor-position.x + self.x < margin {
                self.x = - cursor-position.x + margin;
            } else if cursor-position.x + self.x > parent.width - margin - self.text-cursor-width {
                self.x = parent.width - cursor-position.x - margin - self.text-cursor-width;
            }
        }
    }
}

export component VideoInputBox inherits Rectangle {

    in property <string> name <=> vt.text;
    in property <length> boxwidth <=> box.max-width;
    in-out property <string> val <=> box.text;
    in property <InputType> input_type <=> box.input-type;

    HorizontalLayout {
        vt := VideoText {
            vertical-alignment: center;
            horizontal-alignment: left;
            text: "text:";
        }

        VerticalLayout {
            alignment: center;
            box := InputTextBox {
                text: "0";
            }
        }
    }
}
