import { Button, ScrollView, ComboBox } from "std-widgets.slint";
import { Styles } from "styles.slint";

component VideoText inherits Text {
    text: "example text";
    font-size: 12px;
    font-weight: 600;
    color: Styles.video_color;
}

component VideoButton inherits Rectangle {

    in property <string> text;

    pure callback toggle-play-pause();

    width: Math.max(content.width + Styles.padding * 2, 100px);
    height: content.height + Styles.padding * 2;
    border-radius: 8px;
    background: Styles.video_gradient;
    border-width: ta.has-hover ? 2px : 1px;
    border-color: Styles.video_color;

    content := VideoText {
        text: text;
        font-weight: ta.has-hover ? 1000 : 600;
    }

    ta := TouchArea {
        clicked => toggle-play-pause();
    }
}

component VideoComboBox inherits Window {
    background: transparent;

    in property <[string]> options: ["first", "second", "third"];
    ComboBox {
        model: options;
        current-value: options[0];
    }
}

export component VideoControls inherits Window {

    in property <[string]> video_sources: ["Camera 1", "Camera 2", "Video File"];
    in property <bool> playing: false;
    pure callback toggle-play-pause <=> play_button.toggle-play-pause;

    HorizontalLayout {
        HorizontalLayout {
            alignment: start;
            spacing: 5px;
            play_button := VideoButton {
                text: playing ? "Pause" : "Play";
            }

            screenshot_button := VideoButton {
                text: "Screenshot";
            }
        }

        HorizontalLayout {
            alignment: end;
            spacing: 5px;
            VideoText {
                vertical-alignment: center;
                horizontal-alignment: right;
                text: "Select video source:";
            }

            VideoComboBox {
                options: root.video_sources;
            }
        }
    }
}
