import { Button, ScrollView, ComboBox } from "std-widgets.slint";
import { Styles } from "styles.slint";
import {
    VideoComboBox,
    VideoButton,
    VideoText,
    InputTextBox,
    ChooseDirButton,
    VideoInputBox,
    MetricText,
} from "components.slint";



component FirstRow inherits HorizontalLayout {
    in property <[string]> video_sources <=> sources.options;
    in-out property <int> curr_video_source <=> sources.current-index;
    in property <[string]> fps <=> framerates.options;
    in-out property <int> curr_fps <=> framerates.current-index;
    in property <bool> playing: false;

    pure callback toggle-play-pause <=> play_button.clicked;
    pure callback take-screenshot <=> screenshot_button.clicked;
    callback selected-video-source <=> sources.selected;
    callback selected-framerate <=> framerates.selected;

    HorizontalLayout {
        HorizontalLayout {
            alignment: start;
            spacing: 5px;
            play_button := VideoButton {
                text: playing ? "Pause" : "Play";
            }

            screenshot_button := VideoButton {
                text: "Screenshot";
            }
        }

        HorizontalLayout {
            alignment: end;
            spacing: 5px;
            VideoText {
                vertical-alignment: center;
                horizontal-alignment: right;
                text: "Source:";
            }

            sources := VideoComboBox {
                selected(value) => {
                    debug("Selected video source: ", value);
                }
            }

            VideoText {
                vertical-alignment: center;
                horizontal-alignment: right;
                text: "FPS:";
            }

            framerates := VideoComboBox {
                selected(value) => {
                    debug("Selected framerate: ", value);
                }
            }
        }
    }
}

component SecondRow inherits HorizontalLayout {

    in-out property <string> output_dir <=> ib.val;

    callback choose-output-dir <=> cd.choose-output-dir;

    HorizontalLayout {
        alignment: stretch;
        spacing: 5px;
        ib := VideoInputBox {
            alignment <=> parent.alignment;
            name: "Output directory:";
            val: "/home/root/foo";
        }

        cd := ChooseDirButton { }
    }
}

component ThirdRow inherits HorizontalLayout {

    in-out property <length> noise_x: x.val.to-float() * 1px;
    in-out property <length> noise_y: y.val.to-float() * 1px;
    in-out property <length> noise_w: w.val.to-float() * 1px;
    in-out property <length> noise_h: h.val.to-float() * 1px;
    in-out property <int> number_of_frames: f.val.to-float().round();

    changed noise_x => {
        x.val = noise_x / 1px;
    }
    changed noise_y => {
        y.val = noise_y / 1px;
    }
    changed noise_w => {
        w.val = noise_w / 1px;
    }
    changed noise_h => {
        h.val = noise_h / 1px;
    }

    HorizontalLayout {
        alignment: start;
        spacing: 5px;
        x := VideoInputBox {
            name: "x left:";
            boxwidth: 20mm;
            val: 0;
            input_type: number;
            edited => {
                root.noise_x = self.val.to-float() * 1px;
            }
        }

        y := VideoInputBox {
            name: "y top:";
            boxwidth: 20mm;
            val: 0;
            input_type: number;
            edited => {
                root.noise_y = self.val.to-float() * 1px;
            }
        }

        w := VideoInputBox {
            name: "width:";
            boxwidth: 20mm;
            val: 0;
            input_type: number;
            edited => {
                root.noise_w = self.val.to-float() * 1px;
            }
        }

        h := VideoInputBox {
            name: "height:";
            boxwidth: 20mm;
            val: 0;
            input_type: number;
            edited => {
                root.noise_h = self.val.to-float() * 1px;
            }
        }

        f := VideoInputBox {
            name: "frames:";
            boxwidth: 20mm;
            val: 50;
            input_type: number;
            edited => {
                root.number_of_frames = self.val.to-float().round();
            }
        }
    }
}

component MetricGrid inherits HorizontalLayout {
    in property <float> temporal_noise;
    in property <float> fixed_pattern_noise;
    in property <float> noise_framecount;
    in property <float> row_noise;
    in property <float> column_noise;

    min-height: 60px;
    GridLayout {
        padding-bottom: 10px;
        padding-top: 10px;
        Row {
            MetricText {
                text: "Temporal noise: " + (root.temporal_noise * 1000).round() / 1000;
            }

            MetricText {
                text: "Fixed pattern noise: " + (root.fixed_pattern_noise * 1000).round() / 1000;
            }

            MetricText {
                text: "Frame: " + root.noise_framecount;
            }
        }

        Row {
            MetricText {
                text: "Row noise: " + (root.row_noise * 1000).round() / 1000;
            }

            MetricText {
                text: "Column noise: " + (root.column_noise * 1000).round() / 1000;
            }
        }
    }
}

export component VideoControls inherits HorizontalLayout {

    in property <[string]> video_sources <=> first_row.video_sources;
    in-out property <int> curr_video_source <=> first_row.curr_video_source;
    in property <[string]> fps <=> first_row.fps;
    in-out property <int> curr_fps <=> first_row.curr_fps;
    in property <bool> playing <=> first_row.playing;

    pure callback toggle-play-pause <=> first_row.toggle-play-pause;
    pure callback take-screenshot <=> first_row.take-screenshot;
    callback selected-video-source <=> first_row.selected-video-source;
    callback selected-framerate <=> first_row.selected-framerate;

    in-out property <string> output_dir <=> second_row.output_dir;

    callback choose-output-dir <=> second_row.choose-output-dir;

    in-out property <length> noise_x <=> third_row.noise_x;
    in-out property <length> noise_y <=> third_row.noise_y;
    in-out property <length> noise_h <=> third_row.noise_h;
    in-out property <length> noise_w <=> third_row.noise_w;
    in-out property <int> number_of_frames <=> third_row.number_of_frames;

    in property <float> temporal_noise <=> fourth_row.temporal_noise;
    in property <float> fixed_pattern_noise <=> fourth_row.fixed_pattern_noise;
    in property <float> noise_framecount <=> fourth_row.noise_framecount;
    in property <float> row_noise <=> fourth_row.row_noise;
    in property <float> column_noise <=> fourth_row.column_noise;

    VerticalLayout {
        first_row := FirstRow { }

        second_row := SecondRow { }

        third_row := ThirdRow { }

        fourth_row := MetricGrid { }
    }
}
