import { Button, ScrollView, ComboBox } from "std-widgets.slint";
import { Styles } from "styles.slint";
import {
    VideoComboBox,
    VideoButton,
    VideoText,
    InputTextBox,
    ChooseDirButton,
} from "components.slint";



component FirstRow inherits Rectangle {
    in property <[string]> video_sources <=> sources.options;
    in-out property <int> curr_video_source <=> sources.current-index;
    in property <[string]> fps <=> framerates.options;
    in-out property <int> curr_fps <=> framerates.current-index;
    in property <bool> playing: false;

    pure callback toggle-play-pause <=> play_button.clicked;
    pure callback take-screenshot <=> screenshot_button.clicked;
    callback selected-video-source <=> sources.selected;
    callback selected-framerate <=> framerates.selected;

    HorizontalLayout {
        HorizontalLayout {
            alignment: start;
            spacing: 5px;
            play_button := VideoButton {
                text: playing ? "Pause" : "Play";
            }

            screenshot_button := VideoButton {
                text: "Screenshot";
            }
        }

        HorizontalLayout {
            alignment: end;
            spacing: 5px;
            VideoText {
                vertical-alignment: center;
                horizontal-alignment: right;
                text: "Source:";
            }

            sources := VideoComboBox {
                selected(value) => {
                    debug("Selected video source: ", value);
                }
            }

            VideoText {
                vertical-alignment: center;
                horizontal-alignment: right;
                text: "FPS:";
            }

            framerates := VideoComboBox {
                selected(value) => {
                    debug("Selected framerate: ", value);
                }
            }
        }
    }
}

component SecondRow inherits Rectangle {

    in-out property <string> output_dir <=> out_dir_box.text;

    callback choose-output-dir <=> cd.choose-output-dir;

    HorizontalLayout {
        alignment: stretch;
        spacing: 5px;
        vt := VideoText {
            vertical-alignment: center;
            horizontal-alignment: left;
            text: "Output directory:";
        }

        VerticalLayout {
            alignment: center;
            out_dir_box := InputTextBox {
                text: "/home/root/foo";
            }
        }

        cd := ChooseDirButton { }
    }
}

export component VideoControls inherits Rectangle {

    in property <[string]> video_sources <=> first_row.video_sources;
    in-out property <int> curr_video_source <=> first_row.curr_video_source;
    in property <[string]> fps <=> first_row.fps;
    in-out property <int> curr_fps <=> first_row.curr_fps;
    in property <bool> playing <=> first_row.playing;

    pure callback toggle-play-pause <=> first_row.toggle-play-pause;
    pure callback take-screenshot <=> first_row.take-screenshot;
    callback selected-video-source <=> first_row.selected-video-source;
    callback selected-framerate <=> first_row.selected-framerate;

    in-out property <string> output_dir <=> second_row.output_dir;

    callback choose-output-dir <=> second_row.choose-output-dir;

    VerticalLayout {
        first_row := FirstRow { }

        second_row := SecondRow { }
    }
}
